# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b88bc22fe20a2526be3c18e0e607d3cf52b49e7cd85d7b2b456c8fd90bcb045a51f0a0825544329e0c1d392c44e82ff6bd1ed636311818288087a5d321f42bd5

test:
  secret_key_base: 60deb0fd8d7d9a302b5a3c289984c9e3253f247a24a306f6c55aaeae66837a15451fdb6eacc5f2dfd2389ec8f634674af448935ba042983dda52d33520eaaa3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
